### ISSUE TITLE
MVP / v1 of WM Tools

### ISSUE THREAD

**Issue by lengyel-arpad85** [interledger/web-monetization-tools#1]
This is meant to be a marketing tool for WME, 
a way to generate buttons, banners and widgets, editable from a frontend, embeddable into any website by copying a script

v1 available elements and their options include:

- button (text, bg color, text color, font, rounding)
- banner  (title, text, bg color, text color, font)
- widget  (title, text, bg color, text color, button text, button colors, font, rounding)

and all of them require 1 wallet address

Should follow this data flow:
![Screenshot from 2024-05-22 16-54-33](https://github.com/interledger/web-monetization-tools/assets/165793743/c7f4d2c0-e310-4724-bfcf-19e9115eff09)

**Comment by lengyel-arpad85** [comment]
Button config, screen recording:

[button.webm](https://github.com/interledger/web-monetization-tools/assets/165793743/7ad3748e-b54a-40db-bfee-faac1c9ff2d3)

**Comment by lengyel-arpad85** [comment]
Banner config screen recording / preview:

[banner.webm](https://github.com/interledger/web-monetization-tools/assets/165793743/2c83c900-4eb7-429e-a832-dbd4d7c5ca1f)

**Comment by lengyel-arpad85** [comment]
Widget config screen recording / preview:

https://github.com/interledger/web-monetization-tools/assets/165793743/7c8e04c4-12e0-4677-baa0-c8d92e632bd6

**Comment by Tymmmy** [comment]
After discussions with Alex - For V1 we will concentrate on Banner and Widget :
- Banner:
     - rounded corners config option
     - add a link to web monetization download: - go to store if browser supported, go to webmonetization.org new page where download instructions are present
     - add link tag for ref=wallet address

- Widget:
  - has customizable title, and subtitle - similar to intercom
  - will open a new page on interledgerpay.com, where the user adds value, WA, note (all in interledger.com)


For auth - we will do grant auth for WA when user tries changing config

**Comment by Tymmmy** [comment]
For future reference - V2 will concentrate on button and exclusive content

- Exclusive content:
    - Hide content until user is web monetized
    - How to check if user is web monetized? https://webmonetization.org/specification/ check if wm is supported section
 
- Button will open same frame as widget

**Comment by lengyel-arpad85** [comment]
https://github.com/user-attachments/assets/836a2564-d159-490b-aff7-232eccae606b

V1 Banner features:

- configurable background, text color & font
- options for where to display (top | bottom) of host page, and option to animate
- banner script also injects a monetization link with defined wallet address, i order to ensure that there is a link to test against to determine if user has WM extension or not
- banner is only displayed if no monetization support detected
- get extension link is auto generated based on browser and is pointing to the extensions page, in a non supported browser the link points to the webmonetization webpage
- visitor has the option to close the banner, this is remembered for that session

Caveats / issues:
- since we can detect web monetization only on a https page, on http the banner is shown regardless of the extension being present or not

**Comment by lengyel-arpad85** [comment]
https://github.com/user-attachments/assets/dd97e793-ad2d-4e38-a358-cee99486a2bb


V1 Widget features:
- configurable background, text color & font
- interledger pay is embeded as a payment solution
- styles for ILPay are passed as parameters to make sure the ILPay matches the widget defined look

Issues:
- after success message redirect some styles are lost / overwritten (easily fixable)
- on any error the buttons redirect to homepage instead of /extension (fixable)
- **!! in Chrome**, session cookies are lost when redirecting to IDP provider, the payment fails (no solution atm)
